/**
 * Dev-only generator. Bundles `@marianmeres/vanilla` into a single, inlinable
 * IIFE (bound to `globalThis.vanilla`) and writes the committed helper
 * `src/template-helpers/vanilla.ts`.
 *
 * Run with: `deno task vendor:vanilla`
 *
 * We use esbuild directly (not `@marianmeres/deno-build`, which is hardcoded to
 * ESM output) because an ESM module cannot be inlined into a classic <script>
 * and consumed. esbuild's `format: "iife"` + `globalName` gives us exactly the
 * global-binding form we need.
 *
 * Neither esbuild nor `@luca/esbuild-deno-loader` are runtime dependencies of
 * emde — they are imported only here and never reach the published `mod.ts`.
 */
import * as esbuild from "esbuild";
import { denoPlugins } from "@luca/esbuild-deno-loader";
import { dirname, fromFileUrl, join } from "@std/path";

/** Pinned vanilla version to vendor. Bump this to refresh. */
const VANILLA_VERSION = "1.6.0";

const HERE = dirname(fromFileUrl(import.meta.url));
const OUT_FILE = join(HERE, "..", "src", "template-helpers", "vanilla.ts");

async function bundleVanilla(): Promise<string> {
	// Temp entry stub: a plain local file esbuild understands, whose single
	// import is resolved by the deno loader plugin.
	const tmpDir = await Deno.makeTempDir({ prefix: "emde_vendor_vanilla_" });
	const entry = join(tmpDir, "entry.ts");
	await Deno.writeTextFile(
		entry,
		`export * from "jsr:@marianmeres/vanilla@${VANILLA_VERSION}";\n`,
	);

	try {
		const result = await esbuild.build({
			plugins: denoPlugins() as unknown as esbuild.Plugin[],
			entryPoints: [entry],
			bundle: true,
			format: "iife",
			globalName: "vanilla",
			minify: true,
			platform: "browser",
			write: false,
		});
		const code = result.outputFiles?.[0]?.text;
		if (!code) throw new Error("esbuild produced no output");
		return code;
	} finally {
		esbuild.stop();
		await Deno.remove(tmpDir, { recursive: true });
	}
}

function buildHelperSource(bundle: string): string {
	// Make the payload safe to drop verbatim inside `<script>...</script>`:
	// neutralize any premature script-close / HTML-comment sequences. These are
	// only ever substrings of JS string/regex literals, where the extra backslash
	// is a harmless redundant escape at runtime.
	const safe = bundle
		.replaceAll("</script", "<\\/script")
		.replaceAll("<!--", "<\\!--")
		.replaceAll("-->", "--\\>");

	// Ensure the global is explicitly exposed regardless of how the IIFE wrapper
	// surfaces its top-level binding.
	const payload = `${safe};globalThis.vanilla=vanilla;`;

	// Embed via JSON.stringify (NOT a template literal): the minified bundle
	// contains backticks and ${...} which would break a template-literal embed.
	const literal = JSON.stringify(payload);

	return `// AUTO-GENERATED by scripts/vendor-vanilla.ts — DO NOT EDIT BY HAND.
// Re-generate with: deno task vendor:vanilla
//
// Vendored @marianmeres/vanilla v${VANILLA_VERSION}
// MIT License, Copyright (c) 2026 Marian Meres — https://jsr.io/@marianmeres/vanilla
//
// NOTE: the bundle is embedded via JSON.stringify (NOT a template literal) on
// purpose — the minified source contains backticks and \${...}. Do not rewrite
// this as a template literal.

const VANILLA_BUNDLE = ${literal};

/**
 * Returns the \`@marianmeres/vanilla\` reactive DOM library as a single,
 * inlinable JavaScript string. Mirrors {@link reboot} (which returns CSS):
 * drop it into a \`<script>\` in the document head.
 *
 * The bundle is a self-contained IIFE that binds the library to
 * \`globalThis.vanilla\`. Client code destructures what it needs:
 *
 * @example
 * \`\`\`ejs
 * <head>
 *   <script><%= _helpers.vanilla() %></script>
 * </head>
 * <body>
 *   <!-- ...markup / <template> widgets... -->
 *   <script>
 *     const { observable, reactTo, fromTemplate, refs } = vanilla;
 *     // wire up reactivity here (runs after the DOM exists)
 *   </script>
 * </body>
 * \`\`\`
 *
 * Notes:
 * - Include it **once per page**.
 * - Your wiring code must run **after** the relevant DOM exists (place it at the
 *   end of \`<body>\`, or guard with \`DOMContentLoaded\`). The library itself has
 *   no load-time side effects and is safe in the head.
 * - Inlining requires a CSP that allows inline scripts (\`script-src 'unsafe-inline'\`
 *   or a nonce/hash). For many-page sites that prefer a shared browser cache,
 *   self-host the library as an external script instead and cache-bust the URL
 *   with {@link versionHash}.
 *
 * @returns The vanilla library as an IIFE JS string (no \`<script>\` wrapper).
 */
export function vanilla(): string {
	return VANILLA_BUNDLE;
}
`;
}

const bundle = await bundleVanilla();
const source = buildHelperSource(bundle);
await Deno.writeTextFile(OUT_FILE, source);

// Normalize with deno fmt so the committed file is fmt-stable (deterministic,
// so re-running the generator still yields identical output).
await new Deno.Command("deno", {
	args: ["fmt", OUT_FILE],
	stdout: "null",
	stderr: "null",
}).output();

const finalSize = (await Deno.stat(OUT_FILE)).size;
console.log(
	`Wrote ${OUT_FILE} (vanilla v${VANILLA_VERSION}, ${finalSize} bytes).`,
);
