export function topInfo(_props) {
	return `
		<aside role="note" style="background-color: silver; margin: -1rem -1rem 1rem -1rem;">
			<small style="display: block; padding: 1rem 1rem 0 1rem;">
				This is an example site generated by
				<a href="https://github.com/marianmeres/emde" target="_blank">@marianmeres/emde</a>.
				Actual content was generated by <a href="https://claude.ai/" target="_blank">Claude AI</a>.
			</small>
			<hr />
		</aside>
	`;
}

import { purpleYellow } from "@marianmeres/design-tokens/themes";

export function topCss(props) {
	return (
		props._helpers.tokensWithReboot(purpleYellow, "theme-") +
		"\nbody { padding: 1rem; }"
	);
}
