export function topInfo(_props) {
	return `
		<div style="background-color: silver; margin: -2rem -2rem 2rem -2rem; padding: 1rem;">
			This is an example site generated by
			<a href="https://github.com/marianmeres/emde" target="_blank">@marianmeres/emde</a>.
			Actual content was generated by <a href="https://claude.ai/" target="_blank">Claude AI</a>.
		</div>
	`;
}

export function topCss(_props) {
	return `
:root {
	--bs-link-color-rgb: 255, 80, 80;
	--bs-link-hover-color-rgb: 255, 0, 0;
}
body {
	padding: 2rem;
}
	`;
}
